source 'https://rubygems.org'

#ruby '2.2.2'

gem 'addressable'
gem 'asciidoctor'
gem 'bcrypt'
gem 'bigdecimal', '1.2.7'
gem 'compass'
gem 'coveralls'
gem 'datamapper'
gem 'data_mapper'
gem 'dm-postgres-adapter', :group => :production
gem 'dm-sqlite-adapter', :group => :development
gem 'e'
gem 'execjs'
gem 'foreman'
gem 'gems'
gem 'haml'
gem 'i18n', '0.7.0'
gem 'jekyll'
gem 'json', '1.8.3'
gem 'liquid'
gem 'maruku'
gem 'minitest', '5.8.0'
gem 'monk'
gem 'nokogiri'
gem 'nokogiri-diff'
gem 'pg', :group => :production
gem 'pony'
gem 'pry'
gem 'puma'
gem 'pygments.rb'
gem 'rack'
gem 'rack-flash3'
gem 'rack-proxy'
gem 'rack-source'
gem "rack-test", require: "rack/test"
gem 'rake', '10.4.2'
gem 'rails', '4.2.3'
gem 'railties', '4.2.3'
gem 'rb-fsevent'
gem 'redcarpet'
gem 'RedCloth'
gem 'rdiscount'
gem 'rspec'
gem 'rubypants'
gem 'rulers'
gem 'sass'
gem 'sass-globbing'
gem 'sequel'
gem 'shotgun'
gem 'simplecov'
gem 'sinatra'
gem 'sinatra-activerecord'
gem 'sinatra-contrib'
gem 'sinatra-flash'
gem 'sinatra-json'
gem 'sinatra_warden'
gem 'slim'
gem 'sqlite3'
gem 'stringex'
gem 'syntax'
gem 'test-unit'
gem 'therubyracer'
gem 'thin'
gem 'tilt', '>= 1.3.4', '~> 1.3'
#gem 'tilt'
gem 'thread_safe', '0.3.5'
gem 'tux'
gem 'tzinfo', '1.2.2'
gem 'warden'
gem 'webgen'
gem 'yard'